name: Actions
on: [push]
jobs:
    process:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - run: |
                  npm install
                  npm run build
              working-directory: ./common
              name: common
            - run: |
                  npm install
                  npm run build
              working-directory: ./app
              name: web
            - run: |
                  npm install
                  npm run build
              working-directory: ./server
              name: server
